# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170217_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='no-author', max_length=80),
        ),
    ]
