# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170301_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_place',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
