# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
