# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0012_book_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
