# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20170510_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
