# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(blank=True, to='books.Comment'),
        ),
    ]
