# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20170516_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='no-author', max_length=255),
        ),
    ]
