# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20170516_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=50),
        ),
    ]
