# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_comment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(choices=[(b'pos', b'pos'), (b'neg', b'neg'), (b'neutral', b'neutral')], default=b'neutral', max_length=50),
        ),
    ]
