# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
