# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20170527_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookmarked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='liked',
        ),
    ]
