# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170217_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='http://placehold.it/200x200', upload_to='users/'),
        ),
    ]
