# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170403_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follwers',
        ),
    ]
