# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_bookhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookhistory',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookhistory',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
