# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20170305_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhistory',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
