# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_bookhistory_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.BookHistory')),
                ('searchs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.Search')),
            ],
        ),
    ]
