# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='books_action',
        ),
        migrations.AddField(
            model_name='history',
            name='books_action',
            field=models.ManyToManyField(to='navigation.BookHistory'),
        ),
        migrations.RemoveField(
            model_name='history',
            name='searchs',
        ),
        migrations.AddField(
            model_name='history',
            name='searchs',
            field=models.ManyToManyField(to='navigation.Search'),
        ),
    ]
