# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_auto_20170510_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('corpus', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='social_data',
            field=models.ManyToManyField(to='navigation.SocialData'),
        ),
    ]
