# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20170510_2349'),
        ('navigation', '0011_auto_20170514_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='bookmarks',
            field=models.ManyToManyField(to='navigation.Bookmark'),
        ),
    ]
