# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='notifications',
            field=models.ManyToManyField(to='navigation.Notification'),
        ),
    ]
