# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0017_auto_20170521_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='history',
            name='has_chosed_topics',
            field=models.BooleanField(default=False),
        ),
    ]
