# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0019_history_preferd_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdata',
            name='provider',
            field=models.CharField(choices=[('twitter', 'twitter'), ('facebook', 'facebook'), ('linkedin', 'linkedin')], max_length=50),
        ),
    ]
