# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0020_auto_20170525_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='social_data',
        ),
    ]
