# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0021_remove_history_social_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='social_data',
            field=models.ManyToManyField(to='navigation.SocialData'),
        ),
    ]
